src/Entity/Book.php
<?php

namespace App\Entity;

use App\Helper\SlugHelper;
use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 128)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 16)]
    private ?string $isbn = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $image = null;

    #[ORM\Column]
    private ?int $pageCount = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $publishedDate = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $shortDescription = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $longDescription = null;

    #[ORM\Column(length: 32)]
    private ?string $status = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt;

    #[ORM\ManyToMany(targetEntity: Author::class, inversedBy: 'books')]
    private Collection $author;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'books')]
    private Collection $category;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->category = new ArrayCollection();
        $this->author = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;
        $this->slug = SlugHelper::slugify($title);

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): static
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getPageCount(): ?int
    {
        return $this->pageCount;
    }

    public function setPageCount(int $pageCount): static
    {
        $this->pageCount = $pageCount;

        return $this;
    }

    public function getPublishedDate(): ?\DateTimeInterface
    {
        return $this->publishedDate;
    }

    public function setPublishedDate(\DateTimeInterface $publishedDate): static
    {
        $this->publishedDate = $publishedDate;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->longDescription;
    }

    public function setLongDescription(string $longDescription): static
    {
        $this->longDescription = $longDescription;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }

    /**
     * @return Collection<int, Author>
     */
    public function getAuthor(): Collection
    {
        return $this->author;
    }

    public function addAuthor(Author $author): static
    {
        if (!$this->author->contains($author)) {
            $this->author->add($author);
        }

        return $this;
    }

    public function removeAuthor(Author $author): static
    {
        $this->author->removeElement($author);

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->shortDescription;
    }

    public function setShortDescription(string $shortDescription): static
    {
        $this->shortDescription = $shortDescription;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getAuthorsList(): string
    {
        $data = [];
        foreach ($this->getAuthor() as $author)
        {
            $data[] = $author->getName();
        }

        return implode(', ', $data);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Service\BookService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/book', name: 'book:')]
class BookController extends AbstractController
{
    public function __construct(private readonly BookService $bookService)
    {
    }

    #[Route('/{slug}', name: 'by-slug')]
    public function bookBySlug(string $slug): Response
    {
        $book = $this->bookService->getBookBySlug($slug);

        return $this->render('book/index.html.twig', [
            'book' => $book
        ]);
    }
}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book info{% endblock %}

{% block body %}
    <div class="container">
        <div class="card mb-6">
            <div class="row no-gutters">
                <div class="col-md-4">
                    {% if book.image is not null %}
                        <img src="{{ '/uploads/books/' ~ book.image }}" class="card-img" alt="...">
                    {% else %}
                        <img src="https://i.pinimg.com/736x/cb/b9/d2/cbb9d2fed961f53a77a5d1b3ec33f104.jpg"
                             class="card-img" alt="...">
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                        <p class="card-text"><small class="text-muted">Authors: {{ book.authorsList }}</small></p>
                        <p class="card-text">{{ book.longDescription }}</p>
                        <p class="card-text"><small class="text-muted">Isbn: {{ book.isbn }}</small></p>
                        <p class="card-text"><small class="text-muted">Page count: {{ book.pageCount }}</small></p>
                        <p class="card-text"><small class="text-muted">Published
                                date: {{ book.publishedDate|date('Y-m-d') }}</small></p>
                        <p class="card-text"><small class="text-muted">
                                <ul>
                                    {% for category in book.category  %}
                                        <li><a href="{{ path('category:by-slug', {'slug': category.slug}) }}">{{ category.name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}